name: LaTeX workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Download and start container
      run: |
        make container
    - name: Lint
      run: |
        make in_docker TARGET=lint
    - name: Build
      run: |
        make in_docker TARGET=main
    - name: Check
      run: |
        make in_docker TARGET=check
    - name: Clean
      run: |
        make clean
    - name: Upload a build artifact
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: build/main.pdf

