name: LaTeX workflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    # See https://github.com/xu-cheng/latex-docker
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest
      options: --workdir /home/latex
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      run: latexmk -interaction=nonstopmode
    - name: Upload a build artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: build/example.pdf
