name: Workflow

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Should this run create a release."
        required: false
        type: boolean
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: "ubuntu-22.04"
    container: ghcr.io/rudenkornk/latex_image:2.0.0
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Id
      run: id
